name: kakao_map_editing_example
description: Demonstrates how to use the kakao_map_editing plugin.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  location: ^4.3.0
  kakaomap_webview: ^0.5.0

  cupertino_icons: ^1.0.2
  get: 4.3.8
  kakao_map_editing:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
