name: kakao_map_editing
description: kakao map editing packages
version: 1.0.1
homepage: https://github.com/baehoons/kakao_map_flutter_packages

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^3.0.1
  location: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
